memory_limit = 2G
max_execution_time = 1800
max_input_time = 1800
upload_max_filesize = 64M
post_max_size = 64M
zlib.output_compression = On
realpath_cache_size = 10M
realpath_cache_ttl = 7200
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 65407
opcache.validate_timestamps = 1
date.timezone = Europe/Amsterdam
